### ISSUE TITLE
Rate check

### ISSUE THREAD

**Issue by ipa-kut** [ipa320/araig_test_stack#10]
Update/check/test all nodes run at at least 100 Hz
- [x]  calculators
- [x]  interpreter
- [x]  runner

**Comment by ipa-rwu** [comment]
Do you want to create a port to change rate from config file?  I think it is more flexible and easy to dubug

**Comment by ipa-kut** [comment]
Well, we will not be changing the rate a lot. We try to find one perfect number and then stick to it for all tests thereafter, so it does not need to be a config.

**Comment by ipa-kut** [comment]
Another thing to check is the rate at which topics are publishing.

* All data topics should publish @100Hz
* But all signal topics should only publish once when the value changes, not repeatedly publish the same value. This is the true behaviour of signal ie: Level shifts are published and then latched.

We need to verify this for every node, and ensure all future nodes adhere to this.

**Comment by ipa-rwu** [comment]
* calculators: hard code
* interpreter: read from config https://github.com/ipa320/araig_test_stack/blob/9b8f0b4ed7fffc052e52de04a8e1b27db521d0b4/araig_interpreters/config/test_interpreters.yaml#L12

**Comment by ipa-rwu** [comment]
https://github.com/ipa320/araig_test_stack/blob/d2a766a24540485e5b4beef019e9d27bc773e094/araig_test_runners/src/base/base_runner.py#L9

**Comment by ipa-kut** [comment]
In whatever manner this is eventually done, it needs to at least be consistent across the packages. Low priority (but incurs technical debt)

**Comment by ipa-kut** [comment]
Closed by https://github.com/ipa320/araig_test_stack/pull/35
