### ISSUE TITLE
Update test tunners

### ISSUE THREAD

**Issue by ipa-kut** [ipa320/araig_test_stack#12]
- [x] Update visio models for all runners -> Redesign the runners (ie The entire model)
- [x] Then refactor code to reflect this

**Comment by ipa-rwu** [comment]
- [ ] test1
- [ ] test1 with emergency braking
- [ ] test4 with goal
- [ ] test4 without goal
- [ ] test5 dynamic obstacle

**Comment by ipa-kut** [comment]
Need to review.

**Comment by ipa-kut** [comment]
Closed by https://github.com/ipa320/araig_test_stack/pull/35
