### ISSUE TITLE
Consider making calculator trigger conditions less strict

### ISSUE THREAD

**Issue by ipa-kut** [ipa320/araig_test_stack#14]
https://github.com/ipa320/araig_test_stack/blob/9b8f0b4ed7fffc052e52de04a8e1b27db521d0b4/araig_calculators/src/difference/diff_pose_temporal.py#L75

For example in the above line, the start signal need not be true in order to stop recording the temporal difference. From a model level we would like to enforce this, but from a component perspective, this is not strictly necessary. 

Removing this gives us more flexibility, but also adds threat of improper execution (although this is heavily model dependent). Which is better? Need not make a change yet, but something to consider.

**Comment by ipa-rwu** [comment]
this is for calculating the displacement of the same object at different time. So it must be a "start" point and "stop" point. So far I didn't see why we need this flexibility
