### ISSUE TITLE
rosbagger: missing the topics that are not publishing yet

### ISSUE THREAD

**Issue by ipa-rwu** [ipa320/araig_test_stack#18]
If we use `rospy.get_published_topic`, we can't get the topics that are not publishing yet

**Comment by ipa-rwu** [comment]
bc0d915
* whitelist* is for the topics not publishing at the beginning.
* blacklist* is for the topics that we don't want 
* other topics will get from *rospy.get_published_topic*

**Comment by ipa-kut** [comment]
Need to discuss this.

**Comment by ipa-kut** [comment]
Suggestion: Experiment to see which topics are not being picked up by autodiscovery.

**Comment by ipa-kut** [comment]
Closed by https://github.com/ipa320/araig_test_stack/pull/35
