### ISSUE TITLE
ros nodes are not killed cleanly

### ISSUE THREAD

**Issue by ipa-rwu** [ipa320/araig_test_stack#19]
First I use `sudo kill -9 rosmaster ` and `sudo kill -9 roscore`
I still can find processes by `ps aux | grep "ros"`

**Comment by ipa-rwu** [comment]
It can help us to check if it is killed clean. I only find this issue once but no more

**Comment by ipa-kut** [comment]
This is just ROS stuff :P Trying to account for it would be the headache of any major ROS project. I say we just get used to `killall -9 rosmaster` and not worry too much.

**Comment by ipa-kut** [comment]
Closed by https://github.com/ipa320/araig_test_stack/pull/35
