### ISSUE TITLE
debug log for calculators

### ISSUE THREAD

**Issue by ipa-rwu** [ipa320/araig_test_stack#21]
* location:
  default: $HOME/.ros/log
  Need to set up $ROS_LOG_DIR if want to save to a different location
* weird folder name
*  if set output to "log", will not show in screen, will save in "node_name+pid+-stdout.log"
* if screen, won't be saved in file

**Comment by ipa-rwu** [comment]
e4aa702
in config.yaml, if define `if_log: "true"`, will save the output from difference calculators

**Comment by ipa-kut** [comment]
Closed by https://github.com/ipa320/araig_test_stack/pull/35
