### ISSUE TITLE
logging mechanism 

### ISSUE THREAD

**Issue by ipa-rwu** [ipa320/araig_test_stack#24]
part of calculators:

- [x] Create a folder, rename the folder with the test result
- [x] logging final result
- [x] save rosparam after each test
- [x] debug logging for calculators if needed
- [x] rosbag

* folder structure:
```
 - $root/robot_name/test_name  
   (~/ARAIG/turtlebot3_sim/test1_braking)
   - Number + date(day_mon_year_h_m_s) + result(failed/succeeded)
     (4_22_02_2021_11_10_36_succeeded/)
     - param_calcultors.yaml 
     - param_runner.yaml 
     - param_interpreters.yaml 
     - bag_video.rosbag
     - result.yaml
     - (log_goal_time.yaml)
```

**Comment by ipa-rwu** [comment]
debug logging for calculators e4aa702
base class for logging 641acb4
create logging folder 1a2f7a6
logging finial result 07321c7
logging rosparam 88973a0
rosbag 471d186 ffd3160 9a3b77d

**Comment by ipa-kut** [comment]
Need to review this, and then discuss.

**Comment by ipa-kut** [comment]
Sleep commands in each logger needs to be review case-by-case.
Example: 
* rosbagger should start record and THEN sleep
* folder_logger maybe does not even need a sleep?
