### ISSUE TITLE
Calculator result logging

### ISSUE THREAD

**Issue by ipa-kut** [ipa320/araig_test_stack#4]
Write the final result to a file (Ex: Braking distance)

Point to consider: Calculators can be used in different ways, and logging depends on each specific test. 
Either dictate the loggig method (never, once, continuous) as a rosparam in the config yaml OR
UI could do this, since it knows the final result availability BUT
UI should not be a logger.

**Comment by ipa-rwu** [comment]
We can have a function:
* input: 
   * "topic"
   * "log trigger singal"
   * "log file name"
* output
  *  "not sure"

data structure:
 * timestamp (from topic)
 * tipic
 * data string

**Comment by ipa-kut** [comment]
Output could be bool, true if succesfully written.

What data is this a structure of?

**Comment by ipa-kut** [comment]
- [ ] Check if rqt_multiplot can save time series data

**Comment by ipa-rwu** [comment]
this log only is used internally. 
e4aa702

**Comment by ipa-kut** [comment]
Closed by https://github.com/ipa320/araig_test_stack/pull/35
