### ISSUE TITLE
Add reset feature to all nodes

### ISSUE THREAD

**Issue by ipa-kut** [ipa320/araig_test_stack#5]
This should only be done when the complete state machine of the entire system has also been considered.
A really long term low priority feature. For now, simply relaunching works effectively.

- [x] calculators  
- [x] interpreter
- [x] runner

**Comment by ipa-rwu** [comment]
- [ ] calculators  
- [ ] interpreter
- [ ] runner

**Comment by ipa-rwu** [comment]
* runner:

**Comment by ipa-kut** [comment]
Closed by https://github.com/ipa320/araig_test_stack/pull/35
