### ISSUE TITLE
Make all topics latched

### ISSUE THREAD

**Issue by ipa-kut** [ipa320/araig_test_stack#6]
- [x] Calculators
- [x] interpreter
- [x] runner

**Comment by ipa-kut** [comment]
Related to #10

**Comment by ipa-rwu** [comment]
just clear why we need this feature
The feature of latching makes sure that **a new subscriber always gets the last message that was published even if the message was published before the subscriber was connected**

**Comment by ipa-rwu** [comment]
- [x] Calculators
- [ ] interpreter
- [ ] runner 

velocity interpreter need to pub velocity all the time

**Comment by ipa-kut** [comment]
Closed by https://github.com/ipa320/araig_test_stack/pull/35
