### ISSUE TITLE
Goal Interpreter - Goal pose dynamic TF publisher frame disappears on RVIZ

### ISSUE THREAD

**Issue by ipa-kut** [ipa320/araig_test_stack#7]
Based on  https://github.com/ipa320/araig_interpreters/blob/835babe094e728b0ebd777fc6365a7acf61bd5ea/launch/test_goal_interpreter.launch#L9

Apparent solution is to increase timeout on RVIZ. Needs more investigation.

Worth investigating since this happens only with dynamic tf broadcasters

**Comment by ipa-rwu** [comment]
fixed in d5b868290d781cf046288a8656adda9b1a11dbb2

**Comment by ipa-kut** [comment]
Need to review

**Comment by ipa-kut** [comment]
Closed by https://github.com/ipa320/araig_test_stack/pull/35
