### ISSUE TITLE
Record params of execution as well

### ISSUE THREAD

**Issue by ipa-kut** [ipa320/araig_test_stack#8]
Rosbag recorder only records topics, not params. Therefore, at the end of the test launch, we need to have a rosparam dump for each run.

However, this dump should be parameterized, as it needs to save a new file for each test run.

**Comment by ipa-rwu** [comment]
88973a0
we only want to save the parameters that belong to the test. So we need to define the namespace. However, they will be saved in separate files.

**Comment by ipa-kut** [comment]
Closed by https://github.com/ipa320/araig_test_stack/pull/35
