### ISSUE TITLE
Add python dependencies

### ISSUE THREAD

**Issue by ipa-kut** [ipa320/araig_test_stack#9]
Need to find an elegant way to include pyhton dependencies such as scipy and asyncio since rosdep does not handle these.

**Comment by ipa-rwu** [comment]
#11

**Comment by ipa-rwu** [comment]
I only add the pkg which rodep can't find in requirement.txt
For example: 
`rosdep resolve python-scipy` 
this return True, then we can add it into package.xml

**Comment by ipa-kut** [comment]
Yeah this is the weird part though. scipy does resolve, but does not install. Did it work for you?

**Comment by ipa-rwu** [comment]
I have no problem with this. What error did you get?

**Comment by ipa-kut** [comment]
That the package could not be found. Harsh had the same problem on noetic. 

Could you please test this on a docker image of ubuntu 18.04 + `sudo apt install ros-melodic-ros-base` (NOTE: Do not install desktop full.)

**Comment by ipa-kut** [comment]
#11 fixes this.
